### ISSUE TITLE
angular modules with require.js

### ISSUE THREAD

**Issue by kcabral43** [carlo-colombo/grunt-angular-modules-graph#2]
Hi,
I'm getting the following error when running against an angular module that is loaded with requirejs. 

app/shared-module.js skipped due to error: ReferenceError: define is not defined

Is requirejs supported or something you are thinking of supporting in a future release?

**Comment by carlo-colombo** [comment]
The error is given because only some variables are defined on the global scope. Files with undefined global variables are ignored. 

I never used requirejs but looking for code on integrating it with angular I suppose that i should include requirejs js where i eval js files. I think that requirejs behaviors are too complicated to be mocked.

Can you give me some real world example of angular modules defined through requirejs integration so I can evaluate if is feasible to support it.

**Comment by kcabral43** [comment]
Hi Carlo, 

I've included a zip with the ToDoMVC app both leveraging angularjs one with and one without require.js for javacript file loading. Let me know if this helps or if you would like more information. 

Thanks for your help. 
-Kevin 

----- Original Message -----

**Comment by carlo-colombo** [comment]
Thank you, I'll take a look

**Comment by carlo-colombo** [comment]
I investigated about requirejs support and I think it's impossible to implement it with the current type of code evaluation. The angular modules are evaluated in a nodejs environment without any browser emulation.

I got some idea about using phantomjs to emulate a browser environment but I will not implement it right now.

**Comment by kcabral43** [comment]
yeah phantomjs is great. I wish that angular had made module loading a first class citizen of angular. It is a requirement for any complex application and source of endless confusion today. Hopefully it will be baked into Angular 2.0. Thanks for having a look, this is a great tool for applications of the size and complexity that I tend to work on. 

----- Original Message -----
